### PR TITLE
Fix building with newer version of prometheus go client

### PR DESCRIPTION
**Pull request by ut0mt8**

### CODE REVIEW

**Comment by andreyev-melo-movile** [comment]
+1

**Comment by ut0mt8** [comment]
You can use my fork. It works in production since 3 month. The author should accept my pr ;)

**Comment by andreyev-melo-movile** [comment]
I did it, thanks a lot @ut0mt8 !

But I add a `+1` here just as a friendly remainder to @stigsb to accept this PR ASAP. ;-)

**Comment by stigsb** [comment]
Thanks for this patch, merging!

**Pull request merged**
